### ISSUE TITLE
Как добавить свой lib для увеличения возможностей?

### ISSUE THREAD

**Issue by snaulX** [RoPi0n/mash-lang#3]
Хочу написать свой lib для увеличения возможностей языка и чтобы я мог подключить из него в программе новые функции. Но как это сделать?

**Comment by RoPi0n** [comment]
В качестве примера можете глянуть runtime/libs/bf

**Comment by snaulX** [comment]
Кстати раз вы здесь отвечаете, то ответьте и на [форуме](forum.mash-lang.tech)

**Comment by RoPi0n** [comment]
Ок

**Comment by snaulX** [comment]
Я как человек почти не знающий паскаль но знающий Java и C# хочу спросить что такое exports ... name ... и как это реализовать на других языках?

**Comment by snaulX** [comment]
и кстати периодически чекайте форум а то вопросов много а ответов почти нет(

**Comment by RoPi0n** [comment]
На данном этапе развития проекта нужен нативный язык, для того чтобы написать либу...
Java & C# увы не подойдут пока.
C/C++/Pascal/Kotlin и другие могут.
