### ISSUE TITLE
Few questions.

### ISSUE THREAD

**Issue by ghost** [RoPi0n/mash-lang#4]
@RoPi0n @snaulX 

**1.** Is Mash compilable? I mean can I compile Mash file to binary file (like C/C++)?

**2.** Where can I find basic documentation?

**Comment by RoPi0n** [comment]
1. Mash runs on a stack VM. it also requires libraries that extend the functionality of the VM.

2. Fully documentation not ready.
You can find ± actually information on Russian here:
http://mash-project.org/docs/

If you want to use project to solve ur tasks or want to develop something for project - we can talk later.
